// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace TitoAlquiler.Migrations
{
    [DbContext(typeof(SistemaAlquilerContext))]
    [Migration("20250310184237_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Alquileres", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("ItemID")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<int>("UsuarioID")
                        .HasColumnType("int")
                        .HasColumnName("usuarioId");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletedAt");

                    b.Property<DateTime>("fechaFin")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaFin");

                    b.Property<DateTime>("fechaInicio")
                        .HasColumnType("datetime2")
                        .HasColumnName("fechaInicio");

                    b.Property<double>("precioTotal")
                        .HasColumnType("float")
                        .HasColumnName("precioTotal");

                    b.Property<int>("tiempoDias")
                        .HasColumnType("int")
                        .HasColumnName("tiempoDias");

                    b.Property<string>("tipoEstrategia")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipoEstrategia");

                    b.HasKey("id");

                    b.HasIndex("ItemID");

                    b.HasIndex("UsuarioID");

                    b.ToTable("Alquileres", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categoria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletedAt");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("Categorias", (string)null);

                    b.HasData(
                        new
                        {
                            id = 1,
                            nombre = "Transporte"
                        },
                        new
                        {
                            id = 2,
                            nombre = "Electrodomestico"
                        },
                        new
                        {
                            id = 3,
                            nombre = "Electronica"
                        },
                        new
                        {
                            id = 4,
                            nombre = "Inmueble"
                        },
                        new
                        {
                            id = 5,
                            nombre = "Indumentaria"
                        });
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Electrodomestico", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("itemId")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<int>("potenciaWatts")
                        .HasColumnType("int")
                        .HasColumnName("potenciaWatts");

                    b.Property<string>("tipoElectrodomestico")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipoElectrodomestico");

                    b.HasKey("id");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.ToTable("Electrodomesticos", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Electronica", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("almacenamientoGB")
                        .HasColumnType("int")
                        .HasColumnName("almacenamientoGB");

                    b.Property<int>("itemId")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<string>("resolucionPantalla")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("resolucionPantalla");

                    b.HasKey("id");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.ToTable("Electronicas", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Indumentaria", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("itemId")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<string>("material")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("material");

                    b.Property<string>("talla")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("talla");

                    b.HasKey("id");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.ToTable("Indumentarias", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Inmueble", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("itemId")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<int>("metrosCuadrados")
                        .HasColumnType("int")
                        .HasColumnName("metrosCuadrados");

                    b.Property<string>("ubicacion")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("ubicacion");

                    b.HasKey("id");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.ToTable("Inmuebles", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Transporte", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("id");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("capacidadPasajeros")
                        .HasColumnType("int")
                        .HasColumnName("capacidadPasajeros");

                    b.Property<int>("itemId")
                        .HasColumnType("int")
                        .HasColumnName("itemId");

                    b.Property<string>("tipoCombustible")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("tipoCombustible");

                    b.HasKey("id");

                    b.HasIndex("itemId")
                        .IsUnique();

                    b.ToTable("Transportes", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.ItemAlquilable", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("categoriaId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("marca")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("modelo")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("nombreItem")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("tarifaDia")
                        .HasColumnType("float");

                    b.HasKey("id");

                    b.HasIndex("categoriaId");

                    b.ToTable("Items");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Usuarios", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<DateTime?>("deletedAt")
                        .HasColumnType("datetime2")
                        .HasColumnName("deletedAt");

                    b.Property<int>("dni")
                        .HasColumnType("int")
                        .HasColumnName("dni");

                    b.Property<string>("email")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("email");

                    b.Property<bool>("membresiaPremium")
                        .HasColumnType("bit")
                        .HasColumnName("membresiaPremium");

                    b.Property<string>("nombre")
                        .HasColumnType("nvarchar(max)")
                        .HasColumnName("nombre");

                    b.HasKey("id");

                    b.ToTable("Usuarios", (string)null);
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Alquileres", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.ItemAlquilable", "item")
                        .WithMany("Alquileres")
                        .HasForeignKey("ItemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("TitoAlquiler.Model.Entities.Usuarios", "usuario")
                        .WithMany("Alquileres")
                        .HasForeignKey("UsuarioID")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("item");

                    b.Navigation("usuario");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Electrodomestico", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.ItemAlquilable", "item")
                        .WithOne()
                        .HasForeignKey("TitoAlquiler.Model.Entities.Categorias.Electrodomestico", "itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Electronica", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.ItemAlquilable", "item")
                        .WithOne()
                        .HasForeignKey("TitoAlquiler.Model.Entities.Categorias.Electronica", "itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Indumentaria", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.ItemAlquilable", "item")
                        .WithOne()
                        .HasForeignKey("TitoAlquiler.Model.Entities.Categorias.Indumentaria", "itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Inmueble", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.ItemAlquilable", "item")
                        .WithOne()
                        .HasForeignKey("TitoAlquiler.Model.Entities.Categorias.Inmueble", "itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categorias.Transporte", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.ItemAlquilable", "item")
                        .WithOne()
                        .HasForeignKey("TitoAlquiler.Model.Entities.Categorias.Transporte", "itemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("item");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.ItemAlquilable", b =>
                {
                    b.HasOne("TitoAlquiler.Model.Entities.Categoria", "categoria")
                        .WithMany("items")
                        .HasForeignKey("categoriaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("categoria");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Categoria", b =>
                {
                    b.Navigation("items");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.ItemAlquilable", b =>
                {
                    b.Navigation("Alquileres");
                });

            modelBuilder.Entity("TitoAlquiler.Model.Entities.Usuarios", b =>
                {
                    b.Navigation("Alquileres");
                });
#pragma warning restore 612, 618
        }
    }
}
